import json
import re
import pandas as pd

# Combined 200 companies financial metrics (1 to 200)
FINANCIAL_DATA = {
    # Batch 1 (1 to 50)
    "sourcefuse technologies": "$93.9M (ARR)",
    "perennial systems": "$1.2M (ARR)",
    "ib hubs": "$5M (funding)",
    "estuate": "$75.9M (ARR)",
    "colruyt india": "$5.2B (valuation)",
    "elsner technologies": "$1.8M (ARR)",
    "windmill": "$15M (ARR)",
    "pyxis one": "$209M (funding)",
    "qbrainx inc": "$29.5M (ARR)",
    "recro": "$4.5M (ARR)",
    "vfi slk": "$600M (valuation)",
    "infrasoft technologies": "$45M (ARR)",
    "areteans": "$47M (ARR)",
    "antier solutions": "$3M (funding)",
    "nitor infotech": "$30M (ARR)",
    "beyond key": "$10M (ARR)",
    "altudo": "$75M (ARR)",
    "wunderman thompson msc": "$10.5B (valuation)",
    "hanu software": "$72.5M (ARR)",
    "claim genius": "$10.6M (funding)",
    "scikey": "$5M (funding)",
    "svam international": "$35M (ARR)",
    "cheers interactive": "$100M (ARR)",
    "secure-24": "$169.5M (ARR)",
    "mjunction services": "$42M (ARR)",
    "zendrive": "$60M (funding)",
    "dimagi": "$51.6M (ARR)",
    "loconav": "$47M (funding)",
    "cogent infotech": "$65M (ARR)",
    "it by design": "$25M (ARR)",
    "stanley david and associates": "$50M (ARR)",
    "mygate": "$250M (valuation)",
    "great place it services": "$3M (ARR)",
    "utthunga": "$35M (ARR)",
    "grassroots": "$4M (ARR)",
    "increff": "$73M (valuation)",
    "securekloud technologies": "$20M (valuation)",
    "pharmarack": "$10.5M (funding)",
    "adk rage": "$15M (ARR)",
    "hubilo": "$153M (funding)",
    "auzmor": "$7.4M (ARR)",
    "capsitech": "$4.5M (ARR)",
    "innive inc": "$10M (ARR)",
    "dsm soft": "$8M (ARR)",
    "customer centria": "$3M (ARR)",
    "enhance it": "$27.4M (ARR)",
    "teksystems global services in india": "$7B+ (ARR)",
    "delphix": "$120M (funding)",
    "thoughtspot": "$4.2B (valuation)",
    "corestack": "$350M (valuation)",

    # Batch 2 (51 to 100)
    "solugenix": "$17M (ARR)",
    "visible alpha": "$68M (funding)",
    "flytxt": "$37.3M (ARR)",
    "fourth dimension solutions": "$2.2M (ARR)",
    "novopay": "$4.5M (ARR)",
    "dassault systems": "$31.7B (valuation)",
    "ntt data": "$42.2B (ARR)",
    "data glove": "$90.5M (valuation)",
    "replicon": "$20M (funding)",
    "vaave": "$766K (funding)",
    "sentieo": "$68.5M (funding)",
    "capricot technologies": "$30M (ARR)",
    "shorewise consulting": "$2.5M (ARR)",
    "cleo": "$500M (valuation)",
    "appventurez": "$4.5M (ARR)",
    "incture": "$25M (ARR)",
    "pramati technologies": "$10M (ARR)",
    "knackforge": "$3.5M (ARR)",
    "mangoapps": "$19.6M (ARR)",
    "workindia": "$91M (valuation)",
    "fulcrum digital inc": "$100M (ARR)",
    "hpl": "$240M (valuation)",
    "net business solutions": "$3M (ARR)",
    "bpo convergence": "$9M (ARR)",
    "compumatrice": "$2M (ARR)",
    "a-1 technology": "$36.8M (ARR)",
    "rategain": "$1.2B (valuation)",
    "zenwork": "$163M (funding)",
    "condeco": "$528M (funding)",
    "mtx group": "$50M (ARR)",
    "niit technologies": "$9.4B (valuation)",
    "smartek21": "$75.7M (ARR)",
    "transact global": "$4M (ARR)",
    "fime": "$50M (ARR)",
    "grasko solutions": "$8.5M (ARR)",
    "arcadia": "$1.5B (valuation)",
    "vymo": "$45M (funding)",
    "absolutdata analytics": "$40M (ARR)",
    "mindfire solutions": "$7M (ARR)",
    "urban ladder": "$115M (funding)",
    "deskera": "$250M (valuation)",
    "trilogy innovations": "$4M (ARR)",
    "ginesys": "$10M (funding)",
    "reltio": "$1.7B (valuation)",
    "erevmax": "$15M (ARR)",
    "julia computing": "$127M (funding)",
    "sirionlabs": "$1B (valuation)",
    "talisma": "$66.4M (funding)",
    "uniphore": "$2.5B (valuation)",
    "srs web solutions": "$8M (funding)",

    # Batch 3 (101 to 200)
    "loco": "$200M (valuation)",
    "softnautics": "$4M (ARR)",
    "pathlock": "$20M (funding)",
    "safexpay": "$100M (valuation)",
    "vyom labs": "$25M (ARR)",
    "altruista health": "$40M (ARR)",
    "suntec business solutions": "$96.3M (ARR)",
    "concentrix tigerspike": "$9.6B (valuation)",
    "rapidvalue": "$10M (ARR)",
    "aufait technologies": "$27M (ARR)",
    "kilowott": "$24.9M (ARR)",
    "quinbay": "$69M (ARR)",
    "locuz": "$42M (ARR)",
    "microlise": "$70M (valuation)",
    "cognologix technologies": "$23.3M (ARR)",
    "abzooba": "$1.2M (ARR)",
    "envestnet": "$3.49B (valuation)",
    "quytech": "$5M (ARR)",
    "sun life": "$29B (valuation)",
    "umbrella infocare": "$8.2M (ARR)",
    "webskitters technology solutions": "$6.2M (ARR)",
    "artoon solutions": "$2.2M (ARR)",
    "data dynamics": "$12.8M (ARR)",
    "bob tech solutions": "$2M (ARR)",
    "shipsy": "$32M (funding)",
    "wavicle data solutions": "$105M (ARR)",
    "atem software solutions": "$1.5M (ARR)",
    "amelia": "$80M (valuation)",
    "puresoftware": "$94.5M (valuation)",
    "xto10x": "$25M (funding)",
    "orcapod": "$8M (ARR)",
    "betterplace": "$250M (valuation)",
    "altezzasys systems": "$5M (ARR)",
    "eka software solutions": "$450M (valuation)",
    "srinsoft technologies": "$23M (ARR)",
    "unilog": "$10M (ARR)",
    "pavilion": "$15M (ARR)",
    "mindgate solutions": "$200M (valuation)",
    "spenmo": "$500M (valuation)",
    "senecaglobal": "$15M (ARR)",
    "objectfrontier software": "$62M (ARR)",
    "simplify healthcare": "$98.5M (ARR)",
    "qseap infotech": "$3M (ARR)",
    "mastersoft erp solutions": "$8M (ARR)",
    "tuyasmart india": "$1.02B (valuation)",
    "decision minds": "$29M (ARR)",
    "successive technologies": "$23M (ARR)",
    "suki": "$500M (valuation)",
    "eton solutions lp": "$108M (funding)",
    "kaleyra": "$100M (valuation)",
    "workfusion": "$1B (valuation)",
    "psrtek": "$3.5M (ARR)",
    "pentagon system and services": "$12M (ARR)",
    "crave infotech": "$15M (ARR)",
    "innefu labs": "$30M (funding)",
    "sedin technologies": "$20M (ARR)",
    "niftel communications": "$2M (ARR)",
    "sugarbox networks": "$70M (funding)",
    "opus consulting solutions": "$30M (ARR)",
    "mahindra satyam bpo": "$4.5B (valuation)",
    "isource ites": "$1.5M (ARR)",
    "thirdware solution inc": "$120M (ARR)",
    "genisys group": "$35M (ARR)",
    "brane enterprises": "$25M (ARR)",
    "adarsh solutions": "$2M (ARR)",
    "net solutions": "$10M (ARR)",
    "airdit software services": "$1.2M (ARR)",
    "terralogic": "$15M (ARR)",
    "computer power group": "$20M (ARR)",
    "trellissoft": "$2.5M (ARR)",
    "wobot.ai": "$5.4M (funding)",
    "kami vision": "$10M (funding)",
    "ford pro charging": "$60B (valuation)",
    "reward360 global services.": "$15M (ARR)",
    "sisa": "$20M (ARR)",
    "microobjects": "$1.5M (ARR)",
    "idfy": "$256.4M (valuation)",
    "ck solutions": "$2M (ARR)",
    "appstek": "$12M (ARR)",
    "aissel technologies": "$3M (ARR)",
    "edifecs": "$1.4B (valuation)",
    "netcore cloud": "$136.5M (ARR)",
    "diabsolut inc": "$18M (ARR)",
    "games2win india": "$13M (funding)",
    "itcg solutions": "$2.5M (ARR)",
    "dukaan": "$71M (valuation)",
    "supply wisdom": "$25.2M (funding)",
    "hr": "-",
    "verse innovation": "$5B (valuation)",
    "inapp": "$51.7M (ARR)",
    "tatwa technologies": "$9.4M (ARR)",
    "ospyn technologies": "$3.9M (ARR)",
    "rgi group": "$500M (ARR)",
    "izmo": "$160M (valuation)",
    "weaverbird engineering & technology": "$2M (ARR)",
    "iglobal kpo services": "$1.5M (ARR)",
    "total it global": "$25M (ARR)",
    "claritus management consulting": "$8M (ARR)",
    "xoxoday": "$101M (funding)",
    "axeno": "$3.5M (ARR)",

    # Batch 3 (201 to 300 - Next 100 Companies)
    "rdalabs": "$3.5M (ARR)",
    "writer information": "$120M (ARR)",
    "extentia information technology": "$30M (ARR)",
    "gateway group of companies": "$203M (ARR)",
    "inventive it": "$5M (ARR)",
    "netwoven": "$25.4M (ARR)",
    "abjayon": "$63.8M (ARR)",
    "smart ims": "$94.6M (ARR)",
    "polygon": "$451M (funding)",
    "hal": "$37B (valuation)",
    "nec software solutions": "$323M (ARR)",
    "interra systems": "$22M (ARR)",
    "mysense technologies": "$1.5M (ARR)",
    "sa.global": "$50M (funding)",
    "moolya": "$7.6M (ARR)",
    "lambdatest": "$400M (valuation)",
    "founder and lightning": "$240M (valuation)",
    "innover digital": "$107M (ARR)",
    "naviga india": "$81.6M (ARR)",
    "sriven systems": "$12M (ARR)",
    "eclinical solutions": "$58.1M (ARR)",
    "softura": "$9.5M (ARR)",
    "jagran new media": "$12M (ARR)",
    "srini pharmaceuticals": "$20M (ARR)",
    "palni inc": "$29.9M (ARR)",
    "streamoid": "$1M (funding)",
    "colortokens": "$31.1M (ARR)",
    "fcs software solutions": "$28M (valuation)",
    "gokwik": "$481M (valuation)",
    "acnovate corporation": "$11.5M (ARR)",
    "catalyst business solutions": "$27.9M (ARR)",
    "introlligent": "$8M (ARR)",
    "rang technologies inc": "$59M (ARR)",
    "iflair web technologies": "$24.4M (ARR)",
    "byteridge": "$4.5M (ARR)",
    "zcon solutions": "$21.2M (ARR)",
    "ample technologies": "$195M (ARR)",
    "etg digital": "$10M (ARR)",
    "caastle": "$300M (funding)",
    "kpi partners": "$86.1M (ARR)",
    "vnc digital services": "$8.6M (ARR)",
    "interra information technologies": "$63.1M (ARR)",
    "atidiv": "$7M (ARR)",
    "everyday health group": "$38.5M (ARR)",
    "thinkbridge": "$65.6M (ARR)",
    "intech": "$601M (ARR)",
    "zeomega": "$147M (ARR)",
    "axioned": "$5M (ARR)",
    "gupshup": "$278M (valuation)",
    "esri india": "$35M (ARR)",
    "ducen": "$63M (ARR)",
    "konica minolta business solutions india": "$120M (ARR)",
    "appviewx": "$52M (funding)",
    "it services": "-",
    "ishir": "$46.6M (ARR)",
    "galaxy weblinks inc": "$9M (ARR)",
    "accutech power solutions": "$8.5M (ARR)",
    "c-square info solutions": "$4.5M (ARR)",
    "dixit infotech services": "$33M (ARR)",
    "proximity works": "$10M (ARR)",
    "genzeon": "$88.3M (ARR)",
    "skience": "$18M (ARR)",
    "appiness interactive": "$3.5M (ARR)",
    "webkul": "$59.1M (ARR)",
    "mindcraft software": "$9M (ARR)",
    "conviva": "$300M (valuation)",
    "trell": "$120M (valuation)",
    "accelq": "$25M (ARR)",
    "mobiloitte": "$4.5M (ARR)",
    "quark software": "$68.8M (ARR)",
    "prescient technologies": "$7.2M (ARR)",
    "akal information systems": "$25M (ARR)",
    "strategicerp business automation solutions": "$4.5M (ARR)",
    "brainerhub solutions": "$2.5M (ARR)",
    "ssm infotech solutions": "$7.5M (ARR)",
    "dvg": "$5M (ARR)",
    "shopx": "$102M (valuation)",
    "lumiq": "$51.8M (valuation)",
    "akshay software technologies": "$8M (ARR)",
    "atlan": "$750M (valuation)",
    "data intensity": "$45M (ARR)",
    "newt global consulting": "$68.5M (ARR)",
    "ivalue infosolutions": "$290M (ARR)",
    "apptware": "$24.4M (ARR)",
    "eternus": "$78.9M (ARR)",
    "nest digital": "$17.5M (ARR)",
    "senrysa technologies": "$11.6M (ARR)",
    "imperative business ventures": "$4.7M (ARR)",
    "tacttree llp": "$1.5M (ARR)",
    "crg solutions": "$10.8M (ARR)",
    "logixal inc": "$4.5M (ARR)",
    "hirexa solutions": "$31.8M (ARR)",
    "ivy mobility": "$15M (funding)",
    "credence analytics": "$2.5M (ARR)",
    "pesto tech": "$2M (funding)",
    "securelynkx networks": "$2.5M (ARR)",
    "dckap": "$35.2M (ARR)",
    "paytm insider": "$35M (ARR)",
    "sa technologies": "$98.4M (ARR)",
    "fable fintech": "$29.1M (valuation)"
}

def clean_comp(comp):
    if not comp or pd.isna(comp):
        return ""
    c = str(comp).strip().lower()
    c = re.sub(r'[\s,]+$', '', c)
    return c

def get_net_worth(comp):
    cleaned = clean_comp(comp)
    val = FINANCIAL_DATA.get(cleaned, "-")
    return val if val != "" else "-"

def main():
    print(f"=== Updating Financial Data across all files for 200 companies ===")

    # 1. Update hr_contacts.csv
    csv_path = "hr_contacts.csv"
    df_hr = pd.read_csv(csv_path)
    df_hr['net_worth'] = df_hr['company'].apply(get_net_worth)
    df_hr.to_csv(csv_path, index=False)
    pop_hr = (df_hr['net_worth'] != '-').sum()
    dash_hr = (df_hr['net_worth'] == '-').sum()
    print(f"1. hr_contacts.csv: populated={pop_hr}, dashes={dash_hr}")

    # 2. Update 1800 HR email id list.xlsx
    xlsx_path = "1800 HR email id list.xlsx"
    df_1800 = pd.read_excel(xlsx_path)
    df_1800['net_worth'] = df_1800['Company'].apply(get_net_worth)
    df_1800.to_excel(xlsx_path, index=False)
    pop_xlsx = (df_1800['net_worth'] != '-').sum()
    print(f"2. 1800 HR email id list.xlsx: populated={pop_xlsx}")

    # 3. Update 1800 HR email id list.csv
    csv_1800_path = "1800 HR email id list.csv"
    df_1800.to_csv(csv_1800_path, index=False)
    print(f"3. 1800 HR email id list.csv: populated={pop_xlsx}")

    # 4. Update src/data/contacts.json
    json_path = "src/data/contacts.json"
    with open(json_path, "r", encoding="utf-8") as f:
        contacts = json.load(f)

    for c in contacts:
        c['net_worth'] = get_net_worth(c.get('company', ''))

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(contacts, f, indent=2, ensure_ascii=False)
    pop_json = sum(1 for c in contacts if c.get('net_worth') != '-')
    print(f"4. contacts.json: populated={pop_json}")

    print("=== Successfully updated all 4 files for 200 companies ===")

if __name__ == "__main__":
    main()
